name: Documentation Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run documentation build

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        path: ncs/nrf

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-doc-pip

    - name: Install python dependencies
      run: |
        pip3 install -U pip
        pip3 install -U setuptools
        export PATH="$HOME/.local/bin:$PATH"
        pip3 install -U west
        pip3 install sphinx==3.2.1
        pip3 install breathe==4.22.1
        pip3 install recommonmark==0.6.0
        pip3 install CommonMark==0.9.1
        pip3 install -U sphinxcontrib-mscgen
        pip3 install sphinx-tabs==1.3.0
        pip3 install sphinx-rtd-theme==0.4.3
        pip3 install docutils==0.16

    - name: West init and update
      working-directory: ncs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        west init -l nrf
        west update
        west zephyr-export
